### ISSUE TITLE
Support Facebook

### ISSUE THREAD

**Issue by kseo** [CodeChain-io/codechain-faucet#2]

**Comment by majecty** [comment]
@jhs7jhs See https://faucet.rinkeby.io
They do not ask users to sign their facebook app up.
So I guess that they download raw HTML and parse it

**Comment by hyunsikjeong** [comment]
1. Change the description in the index page. All the texts are focusing on Twitter. Also need to add the example Facebook post.
2. Make the history model general.

**Comment by majecty** [comment]
Landed at #8
